version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: completionist_db
    restart: unless-stopped

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: completionist_db

    ports:
      - "5433:5432"

    volumes:
      - completionist_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  completionist_data:
    driver: local