name: server
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  postgres: ^3.5.9
  http: ^1.6.0
  shared_preferences: ^2.5.4

dev_dependencies:
  dart_frog_lint: ^0.1.0
  mocktail: ^1.0.3
  test: ^1.25.5
